name: C++ SFML (Ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install SFML via APT
      run: |
        sudo apt update
        sudo apt install -y libsfml-dev

    - name: Build
      run: g++ -std=c++20 src/*.cpp -lsfml-graphics -lsfml-window -lsfml-system -o program

    - name: Test
      run: ./program --test
      continue-on-error: true
